# Generated by Django 3.1.7 on 2021-02-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
